# -*- coding: utf-8 -*-
"""extractRRinterval-datasetWESAD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N1aHYXq2Tepu8lpC-458_hHvZjHwiTqf
"""

pip install biosppy

from google.colab import drive
drive.mount('/content/drive/')

import numpy as np
from biosppy.signals import ecg

def get_rr_intervals(sampling_rate):
  with open("/content/drive/MyDrive/DATASET-WESAD/S10_respiban.txt", "r") as file:
    lines = file.readlines()

  header_end = lines.index("# EndOfHeader\n")
  data_lines = lines[header_end + 1:]

  ecg_data = []
  for line in data_lines:
    values = line.strip().split("\t")
    ecg_value = int(values[2])
    ecg_data.append(ecg_value)

  out = ecg.ecg(signal=ecg_data, sampling_rate=sampling_rate)
  rpeaks_indices = out["rpeaks"]

  rr_intervals = np.diff(rpeaks_indices) / 1000

  return rr_intervals

rr_intervals = get_rr_intervals(sampling_rate=700)

np.set_printoptions(threshold=np.inf)

num = "S10"
print(f"Detected RR Intervals {num}:", rr_intervals)